# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "dev", "main"]
  pull_request:
    branches: [ "dev", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: build
      run: |
        docker-compose up --build -d
        docker exec-it cash-manager-db bash
        pytest
